### ISSUE TITLE
Hi, a question about metirc_cal.py

### ISSUE THREAD

**Issue by Jack-bo1220** [ZhilyZhang/MECNet#1]
In metric_cal.py
FN = col_sum - TP
FP = raw_sum - TP
precision = TP[1] / col_sum[1]
recall = TP[1] / raw_sum[1]

but precision should be calculated by TP/TP+FP
and recall should be calculated by TP/TP+FN

it seems an error.

**Comment by zhilyzhang** [comment]
Thanks a lot, I fixed this error.
